from __future__ import annotations

import datetime as dt
import html
import json
from pathlib import Path
from typing import Any

from .config import Channel
from .store import load_records


def render_site(
    *,
    data_path: Path,
    channels: list[Channel],
    settings: dict[str, Any],
    docs_dir: Path,
) -> None:
    records = load_records(data_path)
    docs_dir.mkdir(parents=True, exist_ok=True)
    (docs_dir / "videos.json").write_text(
        json.dumps({"videos": records}, indent=2, ensure_ascii=True) + "\n",
        encoding="utf-8",
    )
    (docs_dir / "styles.css").write_text(STYLES, encoding="utf-8")
    (docs_dir / "index.html").write_text(
        build_html(records=records, channels=channels, settings=settings),
        encoding="utf-8",
    )


def build_html(records: list[dict[str, Any]], channels: list[Channel], settings: dict[str, Any]) -> str:
    generated_at = _generated_at(records)
    channel_relationships = build_channel_relationships(channels)
    grouped_records = group_records_by_channel(records, channels)
    channel_themes = build_channel_themes(grouped_records)
    channel_tables = "\n".join(
        render_channel_group(
            channel=channel,
            records=channel_records,
            channel_relationships=channel_relationships,
            channel_themes=channel_themes,
        )
        for channel, channel_records in grouped_records
    )
    channel_cards = "\n".join(render_channel_card(channel, records) for channel in channels)
    topic_options = "\n".join(
        f'<option value="{escape(topic)}">{escape(topic)}</option>'
        for topic in sorted({topic for record in records for topic in record.get("topics", [])})
    )
    return f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{escape(settings.get("site_title", "LLM YouTube Landscape Tracker"))}</title>
  <link rel="stylesheet" href="styles.css">
</head>
<body>
  <header>
    <p class="eyebrow">OpenClaw + Python watcher</p>
    <h1>{escape(settings.get("site_title", "LLM YouTube Landscape Tracker"))}</h1>
    <p>{escape(settings.get("site_description", ""))}</p>
    <p class="meta">Last generated: {generated_at}. Scheduled update: daily at 08:00 UTC.</p>
  </header>

  <section class="cards" aria-label="Channel relationships">
    {channel_cards}
  </section>

  <section class="controls" aria-label="Filters">
    <label>Topic
      <select id="topicFilter">
        <option value="">All topics</option>
        {topic_options}
      </select>
    </label>
  </section>

  <main>
    {channel_tables}
  </main>

  <footer>
    <p>Data source: YouTube channel RSS feeds plus SerpApi YouTube transcript results. Summaries, topic labels, and transcript evidence are generated by the Python pipeline from transcript text.</p>
  </footer>
  <script>
    const topicFilter = document.getElementById('topicFilter');
    const sections = [...document.querySelectorAll('.channel-table-section')];
    function applyFilters() {{
      const topic = topicFilter.value.toLowerCase();
      for (const section of sections) {{
        let visibleVideos = 0;
        const rows = [...section.querySelectorAll('.video-row')];
        for (const row of rows) {{
          const showRow = !topic || row.dataset.topics.toLowerCase().includes(topic);
          row.hidden = !showRow;
          if (showRow) visibleVideos += 1;
        }}
        for (const row of section.querySelectorAll('.channel-extra-row')) {{
          row.hidden = !!topic;
        }}
        section.hidden = visibleVideos === 0;
      }}
    }}
    topicFilter.addEventListener('input', applyFilters);
  </script>
</body>
</html>
"""


def render_channel_group(
    *,
    channel: str,
    records: list[dict[str, Any]],
    channel_relationships: dict[str, str],
    channel_themes: dict[str, list[str]],
) -> str:
    if not records:
        return ""
    topics = sorted({topic for record in records for topic in record.get("topics", [])})
    video_rows = "\n".join(render_video_row(record) for record in records)
    return f"""<section class="channel-table-section" data-channel="{escape(channel)}" data-topics="{escape(" ".join(topics))}">
  <table class="channel-table">
    <tbody>
      <tr class="channel-title-row">
        <th scope="row">CHANNEL</th>
        <td colspan="2"><strong>{escape(channel)}</strong></td>
      </tr>
      <tr class="video-header-row">
        <th scope="col">LATEST VIDEOS</th>
        <th scope="col">LLM TOPICS</th>
        <th scope="col">TRANSCRIPT-GROUNDED SUMMARY</th>
      </tr>
      {video_rows}
      <tr class="channel-extra-row">
        <th scope="row">CHANNEL LLM THEMES</th>
        <td colspan="2" class="channel-theme-cell">{render_badges(channel_themes.get(channel, []), inline=True)}</td>
      </tr>
      <tr class="channel-extra-row">
        <th scope="row">CHANNEL RELATIONSHIP ACROSS LLM THEMES</th>
        <td colspan="2" class="relationship-cell">{escape(channel_relationships.get(channel, ""))}</td>
      </tr>
    </tbody>
  </table>
</section>"""


def render_video_row(record: dict[str, Any]) -> str:
    published = record.get("published", "")[:10]
    topics = " ".join(record.get("topics", []))
    return f"""<tr class="video-row" data-topics="{escape(topics)}">
        <td><a href="{escape(record.get("url", ""))}" target="_blank" rel="noopener">{escape(record.get("title", ""))}</a><br><small>Published: {escape(published)}</small></td>
        <td>{render_badges(record.get("topics", []))}</td>
        <td>{render_summary_points(record)}</td>
      </tr>"""


def render_badges(topics: list[str], inline: bool = False) -> str:
    if not topics:
        return '<span class="meta">No dominant LLM theme detected yet.</span>'
    class_name = "badge badge-inline" if inline else "badge"
    return " ".join(f'<span class="{class_name}">{escape(topic)}</span>' for topic in topics)


def render_summary_points(record: dict[str, Any]) -> str:
    points = record.get("summary_points") or fallback_summary_points(record)
    items = []
    for point in points[:4]:
        if isinstance(point, dict):
            summary = point.get("point", "")
            evidence = point.get("evidence", "")
        else:
            summary = str(point)
            evidence = ""
        evidence_html = f"<br><em>{escape(evidence)}</em>" if evidence else ""
        items.append(f"<li>{escape(summary)}{evidence_html}</li>")
    source = record.get("transcript_source", "")
    return f"<ul class=\"summary-points\">{''.join(items)}</ul><small>Source: {escape(source)}</small>"


def fallback_summary_points(record: dict[str, Any]) -> list[dict[str, str]]:
    summary = record.get("summary", "")
    evidence = record.get("caption_evidence") or record.get("transcript_excerpt") or ""
    return [{"point": summary, "evidence": evidence}]


def render_channel_card(channel: Channel, records: list[dict[str, Any]]) -> str:
    count = sum(1 for record in records if record.get("channel") == channel.name)
    return f"""<article class="card">
  <h2>{escape(channel.name)}</h2>
  <p>{escape(channel.positioning)}</p>
  <p><strong>LLM role:</strong> {escape(channel.llm_role)}</p>
  <p class="meta">{count} tracked videos</p>
</article>"""


def escape(value: Any) -> str:
    return html.escape(str(value), quote=True)


def group_records_by_channel(records: list[dict[str, Any]], channels: list[Channel]) -> list[tuple[str, list[dict[str, Any]]]]:
    grouped = []
    for channel in channels:
        channel_records = [record for record in records if record.get("channel") == channel.name]
        channel_records.sort(key=lambda record: record.get("published", ""), reverse=True)
        grouped.append((channel.name, channel_records))
    return grouped


def build_channel_themes(grouped_records: list[tuple[str, list[dict[str, Any]]]]) -> dict[str, list[str]]:
    themes: dict[str, list[str]] = {}
    for channel, records in grouped_records:
        counts: dict[str, int] = {}
        for record in records:
            for topic in record.get("topics", []):
                counts[topic] = counts.get(topic, 0) + 1
        themes[channel] = [
            topic
            for topic, _ in sorted(counts.items(), key=lambda item: (-item[1], item[0]))[:6]
        ]
    return themes


def build_channel_relationships(channels: list[Channel]) -> dict[str, str]:
    names = {channel.name for channel in channels}
    defaults = {channel.name: channel.llm_role for channel in channels}
    relationships = {
        "Krish Naik": "Applied education voice: relates to the other channels by turning LLM and generative AI ideas into data-science, RAG, and Python learning workflows.",
        "Andrej Karpathy": "Foundations voice: relates to the other channels by explaining neural-network and transformer building blocks that underpin the applied tutorials, paper analyses, and agent workflows.",
        "Yannic Kilcher": "Research-analysis voice: relates to the other channels by turning papers and model internals into technical critique, complementing practical implementation channels and agent-building demos.",
        "Matthew Berman": "Applied-tooling voice: relates to the other channels by showing how LLMs, agents, and coding tools work in practice, complementing research critique and engineering tutorials.",
        "Nicholas Renotte": "Project-builder voice: relates to the other channels by demonstrating hands-on machine-learning and AI implementation patterns that connect model concepts to working software.",
        "COLE MEDIN": "Agent-automation voice: relates to the other channels by focusing on production-style LLM agents and automations, complementing foundational explanations and broader applied AI tutorials.",
    }
    return {name: relationships.get(name, defaults.get(name, "")) for name in names}


def _generated_at(records: list[dict[str, Any]]) -> str:
    values = [record.get("processed_at", "") for record in records if record.get("processed_at")]
    if values:
        return max(values).replace("T", " ")[:16] + " UTC"
    return dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


STYLES = """
:root {
  color-scheme: light;
  --bg: #f7f7fb;
  --card: #ffffff;
  --ink: #1f2937;
  --muted: #5b6472;
  --line: #dce1ea;
  --accent: #3347ff;
  --badge-bg: #eef1ff;
  --badge-ink: #2437d8;
}
* { box-sizing: border-box; }
body {
  margin: 0;
  font-family: Inter, ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  background: var(--bg);
  color: var(--ink);
}
header, main, footer, .cards, .controls {
  width: min(1400px, calc(100% - 32px));
  margin: 0 auto;
}
header { padding: 48px 0 24px; }
h1 { margin: 0 0 12px; font-size: clamp(2rem, 4vw, 4rem); }
.eyebrow, .meta, small { color: var(--muted); }
.eyebrow { text-transform: uppercase; letter-spacing: .12em; font-weight: 700; }
.cards {
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(240px, 1fr));
  gap: 16px;
  margin-bottom: 24px;
}
.card, .controls, table {
  background: var(--card);
  border: 1px solid var(--line);
  border-radius: 18px;
  box-shadow: 0 10px 30px rgba(31, 41, 55, .06);
}
.card { padding: 18px; }
.card h2 { margin-top: 0; font-size: 1.1rem; }
.controls {
  display: flex;
  flex-wrap: wrap;
  gap: 16px;
  padding: 16px;
  margin-bottom: 24px;
}
label { display: grid; gap: 6px; font-weight: 700; }
select, input {
  min-width: 220px;
  padding: 10px 12px;
  border: 1px solid var(--line);
  border-radius: 10px;
  font: inherit;
}
main { overflow-x: auto; }
table {
  width: 100%;
  border-collapse: collapse;
  overflow: hidden;
}
table.channel-table {
  margin-bottom: 24px;
}
th, td {
  padding: 14px;
  vertical-align: top;
  border-bottom: 1px solid var(--line);
}
td {
  min-width: 190px;
}
th {
  text-align: left;
  background: #eef1ff;
  font-size: .85rem;
  text-transform: uppercase;
  letter-spacing: .05em;
  width: 210px;
  min-width: 210px;
}
tr.channel-title-row th,
tr.channel-title-row td {
  background: #e4e9ff;
}
tr.video-header-row th,
tr.video-row:first-of-type td {
  border-top: 2px solid var(--line);
}
td.relationship-cell {
  line-height: 1.55;
}
table.channel-table .summary-points {
  font-size: .92rem;
}
ul.summary-points {
  margin: 0;
  padding-left: 18px;
}
ul.summary-points li {
  margin-bottom: 10px;
}
ul.summary-points em {
  display: block;
  color: var(--muted);
  margin-top: 3px;
}
a { color: var(--accent); font-weight: 700; }
.badge {
  display: block;
  width: fit-content;
  margin: 0 6px 6px 0;
  padding: 5px 8px;
  border-radius: 999px;
  background: var(--badge-bg);
  color: var(--badge-ink);
  font-size: .82rem;
  font-weight: 700;
}
.badge.badge-inline {
  display: inline-block;
}
footer { padding: 32px 0 48px; color: var(--muted); }
"""
